### ISSUE TITLE
Raw text in editor breaks with inline editing

### ISSUE THREAD

**Issue by anthyeung** [bleistivt/dokuwiki-plugin-mobiletable#1]
First of all, thanks for this great plugin -- really great for making tables mobile-friendly!

I've come across an issue when using mobiletable. When using "!" to activate a mobile table, it seems to break the editor when I do inline editing (see screenshot). The resulting Dokwiki editor show nothing (blank) after I click "Edit", or the raw Markdown will be randomly cut off or garbled. I'm using Greebo, but suspect this is also an issue with Hogfather. This issue does not occur when I click to edit the whole page all at once.

![Screen Shot 2020-08-20 at 8 37 09 PM](https://user-images.githubusercontent.com/25992331/90839772-4db21400-e326-11ea-8053-58531638d80d.png)

I wonder if this has to do with the way the table schema works using the "!", and how Dokuwiki's inline editing function parses the raw Markdown?

https://github.com/bleistivt/dokuwiki-plugin-mobiletable/blob/206767075259bc1870ea56572206cfd89b850d73/action.php#L65-L81

**Comment by bleistivt** [comment]
Thanks for using my plugin!

I believe this happens because the table markup is actually duplicated which messes up the secedit references. This is something I will have to handle using the PARSER_HANDLER_DONE hook: https://www.dokuwiki.org/devel:event:parser_handler_done

I am currently rewriting this plugin so that the table transformation happens on the client, so no markup will be duplicated

**Comment by anthyeung** [comment]
Ah yes, that totally makes sense re: the secedit reference. I'm not very familiar with the Dokuwiki plugin API so can't really contribute, but thanks so much again for your work on this plugin! Looking forward to trying out the new version! :)

**Comment by bleistivt** [comment]
@anthyeung I've just pushed a new version which adds syntax which is more in line with other table plugins (like [sortablejs](https://www.dokuwiki.org/plugin:sortablejs)) and doesn't mess up section editing:

```
<mobiletable 1>
^ Name   ^ Color ^ Size  ^ Speed   ^
^ Item 1   | Red   | Small | 50 km/h |
^ Item 2   | Green | Large | 30 km/h |
</mobiletable>
```

The old syntax still works for the transition to be smooth, it is just recommended to use the new one.

**Comment by anthyeung** [comment]
Amazing! This rewrite is awesome! Thanks again for your work on this plugin!
